xcodeproj '/Users/carl/Desktop/STarBar/STarBar/STarBar/STarBar.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'STarBar' do
	pod 'AFNetworking', '~> 3.0'
end

